conditions: v1
version: "= 0"
if: >  # Forbid running non-PR pushes from pyup bot
  not (type != pull_request AND branch =~ ^pyup\-scheduled\-update\-)

dist: xenial
sudo: required

language: python

python:
- 3.6
- &py37 3.7
- 3.7-dev
- nightly
- &pypy3 pypy3.5

install:
- &upgrade_python_toolset pip install --upgrade pip wheel setuptools
- pip install -r requirements/cython.txt
- pip install -r requirements/ci.txt

script:
- make cov-ci-no-ext
- make cov-ci-aio-debug
- make cov-ci-run

after_success:
 - codecov

_helpers:
- &py37 3.7
- &py37-osx 3.7.1
#########
- &_mainstream_python_base
  python: *py37
- &_reset_steps
  env: {}
  before_install: skip
  install: skip
  script: skip
  after_success: []
- &_lint_base
  stage: &doc_stage_name docs, linting and pre-test checks
  <<: *_mainstream_python_base
  <<: *_reset_steps
  install:
  - *upgrade_python_toolset
  - pip install -U -r requirements/ci.txt
- &_doc_base
  <<: *_lint_base
  install:
  - *upgrade_python_toolset
  - pip install -U -r requirements/doc.txt -r requirements/doc-spelling.txt
  after_failure: cat docs/_build/spelling/output.txt
  addons:
    apt:
      packages:
      - libenchant-dev
- &osx_python_base
  stage: &stage_test_osx_name test under OS X (last chance to fail before deploy available)
  os: osx
  language: generic
  python: *pypy3
  env: &env_pyenv_base
    PYTHON_VERSION: *pypy3
    PATH: ${PYENV_ROOT}/bin:${PATH}
  env: &env_osx_base
    <<: *env_pyenv_base
    PYTHON_VERSION: &py36 3.6.6
    MACOSX_DEPLOYMENT_TARGET: 10.6
    PYTHON_CONFIGURE_OPTS: "'--enable-universalsdk=/ --with-universal-archs=intel'"
  before_install: &install-from-pyenv
  - brew update
  - brew install pyenv || brew upgrade pyenv
  - &ensure_pyenv_preloaded |
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
  - &install_python pyenv install --skip-existing --keep --verbose "$PYTHON_VERSION"
  - &switch_python pyenv shell "$PYTHON_VERSION"
  - &python_version python --version
  before_install: &install-from-python_org
  - export PYTHON_VERSION_LONG=$(git ls-remote --tags git://github.com/python/cpython.git "${PYTHON_VERSION}*" "v${PYTHON_VERSION}*" | grep -v '\^{}$' | grep -v legacy | awk '{print$2}' | sed 's#^refs/tags/##;s#^v##' | grep -v '[abcepr]' | grep "^${PYTHON_VERSION}" | sort -u | tail -n1)
  - export PYTHON_VERSION_SHORT=$(echo ${PYTHON_VERSION_LONG} | awk -F. '{print$1"."$2}')
  - echo "Selected version vars are:"
  - echo "PYTHON_VERSION=${PYTHON_VERSION}"
  - echo "PYTHON_VERSION_SHORT=${PYTHON_VERSION_SHORT}"
  - echo "PYTHON_VERSION_LONG=${PYTHON_VERSION_LONG}"
  - export PYTHON_INSTALL_PATH="/Library/Frameworks/Python.framework/Versions/${PYTHON_VERSION_SHORT}"
  - export PYTHON_INSTALL_EXE="${PYTHON_INSTALL_PATH}/bin/python${PYTHON_VERSION_SHORT}"
  - export PATH="${PYTHON_INSTALL_PATH}/bin:${PATH}"
  - export PYTHON_VENV_PATH="${HOME}/virtualenv/python${PYTHON_VERSION_SHORT}"
  - env
  - curl -Lo "/tmp/python-${PYTHON_VERSION_LONG}.pkg" -C - "https://www.python.org/ftp/python/${PYTHON_VERSION_LONG}/python-${PYTHON_VERSION_LONG}-macosx10.6.pkg" && sudo installer -pkg "/tmp/python-${PYTHON_VERSION_LONG}.pkg" -target / && rm -f "/tmp/python-${PYTHON_VERSION_LONG}.pkg"
  - ls "${PYTHON_INSTALL_PATH}/bin"
  - export VENV_CMD=$(command -v virtualenv 2>/dev/null || command -v pyvenv 2>/dev/null || echo "${PYTHON_INSTALL_EXE} -m venv")
  - |
    if [[ "${VENV_CMD}" =~ virtualenv$ ]]
    then
        export VENV_CMD="${VENV_CMD} -p '${PYTHON_INSTALL_EXE}'"
    fi
  - echo "${VENV_CMD}"
  - ${VENV_CMD} "${PYTHON_VENV_PATH}"
  - . "${PYTHON_VENV_PATH}/bin/activate"
  - curl https://bootstrap.pypa.io/get-pip.py | python
  - *python_version
  - pip --version
  before_cache:
  - brew --cache
- &generic_deploy_base
  stage: &deploy_stage_name deploy (PYPI upload itself runs only for tagged commits)
  <<: *_mainstream_python_base
  deploy: &deploy_step
    provider: pypi
    # `skip_cleanup: true` is required to preserve binary wheels, built
    # inside of manylinux1 docker container during `script` step above.
    skip_cleanup: true
    # `skip-existing: true` is required to skip uploading dists, already
    # present in PYPI instead of failing the whole process.
    # This happens when other CI (AppVeyor etc.) has already uploaded
    # the very same dist (usually sdist).
    skip-existing: true
    user: aio-libs-bot
    password:
      # Encrypted with `travis encrypt -r aio-libs/aiohttp --api-endpoint 'https://api.travis-ci.com/'`:
      secure: bWF8GkGmjxfisMx+LqOmZgf9EXPT4yBMhiIbN+rU5gs53PJJyn1r287c5zEijnIHlpQaJVwWJ9ZFl1n34y37P1yvhlz0M6esr5K10B9fJ6nkUoAivtOWARcHLQ3bC+WGC/V9S0v0pZ11qFuSNzJzFZqfRabRw0H8muVWGhuBuYp97EdJWCdSNpXqsj2Ts8ytPMYv+5m3iPgXq833svFbWRjZ+HgX8HwvF2lo+ej+tsFJNACbQmj+eQDGlWQZzP2s4/3grHivd2retpqfW1cYgZaZX68/UB2ghsCtkxhcNpGaM8I/n3udAHkPSqz3MC2FJL0RdkyvQ8UZkcmcisQxz0voQM25995BHGWktwpDh7BxFtGJishXV7hiFz9zVOZLM9u5AzIO4hoN770SsZDewWdhzowXPYT8DXiHVg+roEkszg8FeBmisx1cw34CK9H0iLUSQ9EF2vuz8T4bqEpbT6Fyta90wZTvJ7GpJ4yXJXR6VAvLgiX4zXeFdx/4aViz3UzkDJ06qieRuZJWfQ9u2lDxJfqHEVy5IxM5iACagP1XayJiVIN0uFRxNElxTlCMope6ICCOu9fhcGnF15XNw5YpFPYYvph3JU1vC8cYw7ypg8LQGryp1fNM9SXWaGTiV+J/yvsynFiXX6QiyGOwSBIJ9XjZEfRd8i9HaGHw2cw=
    # Although Travis CI instructs `setup.py` to build source distribution,
    # which is default value for distribution option (`distribution: sdist`),
    # it will also upload all wheels we've previously built in manylinux1
    # docker container using `twine upload -r pypi dist/*` command.
    # Also since commit https://github.com/travis-ci/dpl/commit/90b5e39
    # it is default that Travis PYPI provider has `skip_upload_docs: true`
    # set by default.
    # Besides above, we don't do cleanup of `dist/*`, because it's being done
    # by Travis CI PYPI deployment provider after upload, unconditionally.
    on:
      tags: true
      all_branches: true
- &osx_pypi_deploy_base_1011
  <<: *osx_python_base
  <<: *generic_deploy_base
  name: &env_os1011_msg Build and deploy to PYPI of OS X 10.11 binary wheel
  osx_image: xcode7.3
  script: skip
  after_success: []
  env: &env_py36_common
    PYTHON_VERSION: 3.6.3
  deploy:
    <<: *deploy_step
    skip_cleanup: false
    distributions: bdist_wheel
- &osx_pypi_deploy_base_1012
  <<: *osx_pypi_deploy_base_1011
  name: &env_os1012_msg Build and deploy to PYPI of OS X 10.12 binary wheel
  osx_image: xcode8.1
  env: *env_py36_common
- &osx_pypi_deploy_base_1010
  <<: *osx_pypi_deploy_base_1011
  name: &env_os1010_msg Build and deploy to PYPI of OS X 10.10 binary wheel
  osx_image: xcode6.4
  env: *env_py36_common

env:
  global:
    PYENV_ROOT: ${HOME}/.pyenv

os: linux

jobs:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: nightly

  include:
  - python: 3.5
    env:
      PYTEST_ADDOPTS: -n0

  - <<: *_doc_base
    name: Checking docs spelling
    script:
    - make doc-spelling

  - <<: *_doc_base
    name: Checking Towncrier fragments
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/cython.txt
    - pip install -r requirements/ci.txt
    - pip install -r requirements/towncrier.txt
    script:
    - towncrier --yes

  - <<: *_lint_base
    name: Linting source code with flake8
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/flake.txt
    script:
    - flake8 aiohttp examples tests

  - <<: *_lint_base
    name: Linting source code with mypy
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/cython.txt
    - pip install -r requirements/ci.txt
    script:
    - mypy aiohttp

  - <<: *_lint_base
    name: Verifying distribution package metadata
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/cython.txt
    - pip install -r requirements/ci.txt -r requirements/doc.txt
    script:
    - python setup.py check --metadata --restructuredtext --strict --verbose sdist bdist_wheel
    - twine check dist/*

  - <<: *_lint_base
    name: Making sure that CONTRIBUTORS.txt remains sorted
    language: minimal
    install:
    - skip
    script:
    - LC_ALL=C sort -c CONTRIBUTORS.txt

  - <<: *osx_python_base
    python: &py35 3.5.3
    env: &osx_env_py35
      <<: *env_osx_base
      PYTHON_VERSION: *py35
      PYTEST_ADDOPTS: -n0
  - <<: *osx_python_base
    python: *py36
    env: &osx_env_py36
      <<: *env_osx_base
      PYTHON_VERSION: *py36
  - <<: *osx_python_base
    python: *py37
    env:
      PYTHON_VERSION: 3.7-dev
  - <<: *osx_python_base
    python: *py37
    env: &osx_env_py37
      <<: *env_osx_base
      PYTHON_VERSION: *py37
  # pypy3.5-5.10.0 fails under OS X because it's unsupported

  # Build and deploy manylinux1 binary wheels and source distribution
  - <<: *generic_deploy_base
    <<: *_reset_steps
    name: Build and deploy to PYPI of manylinux1 binary wheels for all supported Pythons and source distribution
    dist: trusty
    group: edge
    services:
    - docker
    script:
    - ./tools/run_docker.sh "aiohttp"
    - pip install -r requirements/cython.txt
    - pip install -r requirements/ci.txt  # to compile *.c files by Cython
    deploy:
      <<: *deploy_step

    # Build and deploy MacOS binary wheels for each OSX+Python combo possible
    # OS X 10.10, Python 3.5
  - <<: *osx_pypi_deploy_base_1010
    python: *py35
    env: *osx_env_py35
    # OS X 10.10, Python 3.6
  - <<: *osx_pypi_deploy_base_1010
    python: *py36
    env: *osx_env_py36
    # OS X 10.10, Python 3.7
  - <<: *osx_pypi_deploy_base_1010
    python: *py37
    env: *osx_env_py37
    # OS X 10.11, Python 3.5
  - <<: *osx_pypi_deploy_base_1011
    python: *py35
    env: *osx_env_py35
    # OS X 10.11, Python 3.6
  - <<: *osx_pypi_deploy_base_1011
    python: *py36
    env: *osx_env_py36
    # OS X 10.11, Python 3.7
  - <<: *osx_pypi_deploy_base_1011
    python: *py37
    env: *osx_env_py37
    # OS X 10.12, Python 3.5
  - <<: *osx_pypi_deploy_base_1012
    python: *py35
    env: *osx_env_py35
    # OS X 10.12, Python 3.6
  - <<: *osx_pypi_deploy_base_1012
    python: *py36
    env: *osx_env_py36
    # OS X 10.12, Python 3.7
  - <<: *osx_pypi_deploy_base_1012
    python: *py37
    env: *osx_env_py37

stages:
- *doc_stage_name
- test
- name: *stage_test_osx_name
  if: type IN (api, cron)
- name: *deploy_stage_name
  # This will prevent deploy unless it's a tagged commit:
  if: tag IS present


cache: pip

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
