# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- ?.?

stages:
- stage: prechecks
  displayName: "Pre-Checks"
  jobs:
  - job: precheck-job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersio@0
      versionSpec: '3.6'
      displayName: 'Use Python 3.6'

    - script: |
        sudo apt-get update
        sudo apt-get install libenchant-dev
        pip install -r requirements/doc.txt -r requirements/doc-spelling.txt
        make doc-spelling
      displayName: 'Checking docs spelling'
      env:
        AIOHTTP_NO_EXTENSIONS: 1


- stage: test
  displayName: "Run tests"
  jobs:
  - job: test
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python35-Linux:
          python.version: '3.5'
        Python36-Linux:
          python.version: '3.6'
        Python37-Lunux:
          python.version: '3.7'

    steps:
    - checkout: self
      clean: true
      submodules: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements/cython.txt
        make cythonize
      displayName: 'Install prerequirements'

    - script: |
        pip install -r requirements/ci.txt pytest-azurepipelines
        pip install .
      displayName: 'Install dependencies'

    - script: |
        pytest -c pytest.ci.ini -s -v
      displayName: 'Test'
